# ----------
# GNUmakefile
#
#      Copyright (c) 2008 Marc Munro
#      Fileset:	skit - a database schema management toolset
#      Author:  Marc Munro
#      License: GPL V3
#
# $Id$
# ----------
#

DEFAULT:

%::
	cd ..; $(MAKE) $@

