# ----------
# GNUmakefile
#
#      Copyright (c) 2011 - 2014 Marc Munro
#      Fileset:	skit - a database schema management toolset
#      Author:  Marc Munro
#      License: GPL V3
#
# ----------
#

DEFAULT:

%::
	cd ..; $(MAKE) $@